<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<?php if ($this->getFieldValue()) $hint = false; ?>
<input type='file' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='<?php echo $this->getFieldClass() ?> <?php if($hint){ echo 'webforms-fields-hint';}?>' style='<?php echo $this->getFieldStyle() ?>'
       
       <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
       
       <input name="MAX_FILE_SIZE" type="hidden" value="2000000" />
       <?php if (($hint) && $this->getFieldValue() != '') {?>
       <br/>
       <?php if ($hint) echo $hint; else echo htmlspecialchars($this->getFieldValue()); 
	   }
	   ?>
       
